#include "MyClient.h"
MyClient::MyClient(){}
MyClient::~MyClient(){}

void MyClient::socketConnect()
{
    socket = new QTcpSocket(this);
    connect(socket,SIGNAL(readyRead()),this,SLOT(socketReady()));
    connect(socket,SIGNAL(disconnected()),this,SLOT(socketDisconnected()));
    socket->connectToHost("127.0.0.1", 5555);
}

void MyClient::socketDisconnected(){
    socket->deleteLater();
}

void MyClient::socketReady(){
    if (socket->waitForConnected(500))
    {
        socket->waitForReadyRead(500);
        data = socket->readAll();
    }
}

void MyClient:: socketRecieve()
{
    QFile toSend("/Other/docRecieve.txt");
    if(toSend.open(QIODevice::ReadOnly | QIODevice::Text)) {//Open "read file"
        QByteArray rawFile;
        rawFile = toSend.readAll();

        QDataStream out(data);
        out >> rawFile;
        toSend.close();//close
    }
}

void MyClient:: socketSend(){

    QFile qwe("/Other/myDoc.txt");
    if(qwe.open(QIODevice::WriteOnly | QIODevice::Text)){
        QTextStream out(&qwe);
        out << "This file is generated by Qt\n";
        qwe.close();
    } else {
        qDebug() << "Error";
    }




}
